services:
  bot:
    build: .
    restart: unless-stopped
    ports:
      - '1488:1488'
    volumes:
      - .:/app/project
      - bot_data:/app/project/data
      - /app/.venv

volumes:
  bot_data:
